package org.solace.composeapp.ui.data

import org.solace.composeapp.actor.ActorState
import kotlin.time.Instant

/**
 * UI-friendly representation of actor data for real-time display
 */
data class ActorDisplayData(
    val id: String,
    val name: String,
    val state: ActorState,
    val lastUpdate: Instant,
    val metrics: ActorMetricsData,
    /** Whether this actor is a plain message processor, AI-backed agent, or system service. */
    val agentType: AgentType = AgentType.Standard,
    /** What the actor is currently working on, if anything. */
    val currentTask: TaskInfo? = null,
    /** Short, human-readable description of the agent's role and capabilities. */
    val description: String? = null,
    /** Skills/capabilities this agent offers (shown as chips). */
    val capabilities: List<String> = emptyList()
)

/** Categorizes the underlying behavior of an actor. */
enum class AgentType {
    /** Pure stream/message processor — no chat surface. */
    Standard,

    /** LLM-backed agent — exposes a chat interface. */
    AI,

    /** Infrastructure/system service (logging, metrics, supervision). */
    System
}

/**
 * Describes the unit of work an actor is currently focused on. Updated as work progresses.
 */
data class TaskInfo(
    val title: String,
    val detail: String,
    val startedAt: Instant,
    /** 0..1 — null when the task is open-ended (chat, monitoring, streaming). */
    val progress: Float? = null
)

/**
 * A single line of actor activity, akin to a structured log line.
 */
data class LogEntry(
    val timestamp: Instant,
    val level: LogLevel,
    val message: String
)

enum class LogLevel { Trace, Debug, Info, Warn, Error }

/**
 * One turn in a conversation with an AI-backed actor.
 */
data class ChatMessage(
    val timestamp: Instant,
    val role: ChatRole,
    val content: String
)

enum class ChatRole {
    /** Sent by the human operator interacting with the agent. */
    User,

    /** Generated by the agent itself. */
    Agent,

    /** System / framework message — agent state changes, errors, hints. */
    System
}

/**
 * UI-friendly representation of actor metrics
 */
data class ActorMetricsData(
    val messagesReceived: Long = 0,
    val messagesProcessed: Long = 0,
    val messagesFailed: Long = 0,
    val successRate: Double = 0.0,
    val averageProcessingTime: Double = 0.0,
    val lastProcessingTime: Long = 0,
    val portMetrics: Map<String, Long> = emptyMap(),
    val priorityMetrics: Map<String, Long> = emptyMap()
)

/**
 * System-wide metrics for the actor system
 */
data class SystemMetricsData(
    val totalActors: Int = 0,
    val runningActors: Int = 0,
    val stoppedActors: Int = 0,
    val errorActors: Int = 0,
    val pausedActors: Int = 0,
    val totalMessages: Long = 0,
    val averageResponseTime: Double = 0.0,
    val systemUptime: Long = 0
)
