#!/usr/bin/env python3
"""Generate the GitHub Wiki sidebar (`wiki/_Sidebar.md`).

Scans every page in ``wiki/`` for a ``<!-- topic: NAME -->`` marker on the
first line and groups the pages under their topic, in a fixed topic order.
Pages without a topic marker (and the special ``Home``/``_Sidebar``/``_Footer``
pages) are handled explicitly so the navigation stays stable and predictable.
Topic groups are rendered as collapsible ``<details>`` blocks to match the
wiki publishing style used by the knowledge-base reference project.

Run from CI or locally:

    python tools/wiki/generate_sidebar.py --repo-root .
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Fixed display order for topic groups. Pages whose topic is not listed here
# are appended under a trailing "Other" group so nothing silently disappears.
TOPIC_ORDER = ["Orientation", "Runtime", "Solace AI", "Reference"]

# Pages that are never listed as ordinary entries in the sidebar.
EXCLUDE = {"_Sidebar.md", "_Footer.md", "Home.md"}

TOPIC_RE = re.compile(r"<!--\s*topic:\s*(.+?)\s*-->", re.IGNORECASE)
TITLE_RE = re.compile(r"<!--\s*title:\s*(.+?)\s*-->", re.IGNORECASE)


def page_title(path: Path) -> str:
    """First Markdown H1 (``# ...``) or a humanized filename fallback."""
    head = path.read_text(encoding="utf-8")[:400]
    m = TITLE_RE.search(head)
    if m:
        return m.group(1).strip()
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem.replace("-", " ")


def page_topic(path: Path) -> str | None:
    head = path.read_text(encoding="utf-8")[:400]
    m = TOPIC_RE.search(head)
    return m.group(1).strip() if m else None


def link(path: Path) -> str:
    # GitHub Wiki links pages by filename without extension.
    return f"[{page_title(path)}]({path.stem})"


def build_sidebar(wiki_dir: Path) -> str:
    groups: dict[str, list[Path]] = {}
    for md in sorted(wiki_dir.glob("*.md")):
        if md.name in EXCLUDE:
            continue
        topic = page_topic(md) or "Other"
        groups.setdefault(topic, []).append(md)

    ordered_topics = [t for t in TOPIC_ORDER if t in groups]
    ordered_topics += [t for t in groups if t not in TOPIC_ORDER]

    out = ["<!-- AUTO-GENERATED by tools/wiki/generate_sidebar.py. Do not edit by hand. -->", ""]
    out.append("**[SolaceCore Wiki](Home)**")
    out.append("")
    for topic in ordered_topics:
        out.append("<details>")
        out.append(f"<summary><strong>{topic}</strong></summary>")
        out.append("")
        for md in sorted(groups[topic], key=page_title):
            out.append(f"- {link(md)}")
        out.append("")
        out.append("</details>")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Generate wiki/_Sidebar.md")
    ap.add_argument("--repo-root", default=".", help="Repository root (contains wiki/)")
    args = ap.parse_args(argv)

    wiki_dir = Path(args.repo_root).resolve() / "wiki"
    if not wiki_dir.is_dir():
        print(f"error: {wiki_dir} does not exist", file=sys.stderr)
        return 1

    sidebar = build_sidebar(wiki_dir)
    (wiki_dir / "_Sidebar.md").write_text(sidebar, encoding="utf-8")
    print(f"Wrote {wiki_dir / '_Sidebar.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
